myNextApplication:
  component: "@sls-next/serverless-component@3.7.0"
  inputs:
    build:
      env:
        AUTH0_SECRET: ${env.AUTH0_SECRET}
        AUTH0_BASE_URL: ${env.AUTH0_BASE_URL}
        AUTH0_ISSUER_BASE_URL: ${env.AUTH0_ISSUER_BASE_URL}
        AUTH0_CLIENT_ID: ${env.AUTH0_CLIENT_ID}
        AUTH0_CLIENT_SECRET: ${env.AUTH0_CLIENT_SECRET}

    name:
      defaultLambda: nextjsDefaultLambda
      apiLambda: nextjsApiLambda

    roleArn: ${env.SLS_ROLE_ARN}
    policy: ${env.SLS_POLICY}

    cloudfront:
      distributionId: ${env.SLS_CLOUDFRONT_DISTRIBUTION_ID}
      comment: serverless next.js app

    bucketName: ${env.SLS_BUCKET_NAME}
    bucketRegion: ${env.SLS_BUCKET_REGION}
